version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ghcr.io/schnaq/clojure-yarn-chrome:sha-2433fc0
    steps:
      - checkout
      - run: yarn install
      - run: yarn shadow:sitemap
      - run: head node_modules/lowlight/node_modules/highlight.js/lib/languages/isbl.js
      - run: yarn build
# # Orchestrate our job run sequence
# workflows:
#   build_and_test:
#     jobs:
#       - build
#       - test
