name: Clojure CI
on: [push]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/setup-java@v3
  #       with:
  #         distribution: 'corretto'
  #         java-version: '17'

  #     - name: Setup Clojure
  #       uses: DeLaGuardo/setup-clojure@7.0
  #       with:
  #         cli: latest

  #     - uses: borales/actions-yarn@v3.0.0
  #       with:
  #         cmd: install # will run `yarn install` command
  #     - uses: borales/actions-yarn@v3.0.0
  #       with:
  #         cmd: build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/clojure-lint-action@master
        continue-on-error: true
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: latest
      
      - run: yarn build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: resources/public # The folder the action should deploy.
