name: Build

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: latest
      
      - run: |
          yarn install
          yarn build
          yarn dist:zip

      - name: Upload produced files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist.zip
