name: CI

on:
  push:
    branches-ignore:
      - "main" 
  pull_request:
    branches-ignore:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/clojure-lint-action@master
        continue-on-error: true
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}
