name: Deploy
on: 
  pull_request:
    branches:
      - "main"
      - "add/ci"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download assets from previous job
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: unzip -qo dist.zip -d dist
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: dist/resources/public # The folder the action should deploy.
