name: Deploy
on:
  push:
    branches:
      - "main"
      - "add/circle-ci"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@8.0
        with:
          cli: latest

      - name: Build CLJS->JS
        run: |
          yarn install
          yarn shadow:sitemap
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: resources/public # The folder the action should deploy.
